version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'Quantalabs'
    commit-message:
      prefix: '[dep]'
      prefix-development: '[dep/dev]'
    labels:
      - 'dependencies'